### ISSUE TITLE
Duplicated file field widget after form validation

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/html5_upload#10]
On a site with HTML5 Upload enabled, when the content form has a missing value in any required field, the file field widget gets duplicated, and it's not anymore possible to save the form.

**To reproduce the behavior:**

1. Install and enable HTML5 Upload on your site.
2. Add a File field to a content type, and set the "Number of values" in "Global settings" to "Unlimited".
3. Start creating a node of the content type, and let the (required) Title field empty.
4. Hit the Save button of the form. You see an error message (as expected): "Title field is required."
5. Put something in the Title field and hit the Save button again.

**Actual behavior:**

The form still can't be saved, and you see two error messages:

> The file Array could not be saved. An unknown error has occurred.
> The file in the File field was unable to be uploaded.

Furthermore, the file widget in the form is duplicated. Screenshot:

<img src="https://github.com/backdrop/backdrop-issues/assets/14188307/3a84f0a5-57e6-4f5c-b78f-8d5f0a512419" width="400">

There is also a related message in DBlog:

> Warning: Array to string conversion in check_plain() (line 2080 of path-to/core/includes/bootstrap.inc).

**Expected behavior:**

The form is saved without error.

**Additional information:**

- Backdrop 1.26.1
- Web server and its version: Apache
- PHP version: 8.0.30
- Database sever and its version: 10.6.12-MariaDB

**Comment by laryn** [comment]
@olafgrabienski Can you test the linked PR?

**Comment by olafgrabienski** [comment]
@laryn Thank you very much for the PR! Just tested: it fixes the issue for me.

**Comment by laryn** [comment]
I'm not certain of why this `add one final empty upload` bit of code was there -- but am **guessing** it is maybe unnecessary due to Backdrop's auto-upload / AJAX upload functionality. If it's possible to turn that auto-upload functionality off it's maybe worth testing it without that enabled, too.

**Comment by laryn** [comment]
@olafgrabienski No rush but when you get a chance let me know if your testing of this PR "in the wild" is successful.

**Comment by olafgrabienski** [comment]
@laryn Sure, I've had a look in DBlog of the site in question which has been running with the PR for 10 days, and I didn't find any issues. And I just heard from a site editor, they didn't notice any issues either. So yes, I'd say the testing is successful!

**Comment by laryn** [comment]
@olafgrabienski Thanks! I've merged and made a new release.
