### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by danksearle** [backdrop-contrib/html5_upload#12]
It would be nice to see some clues or examples of using this in the doc. I installed it, and it works, but I have no idea what I have to do in my JS or CSS to make the file field look like I can drag and drop into it.

**Comment by laryn** [comment]
@danksearle  I'm not sure exactly what you're after, but if we figure it out together maybe you can add the details in the Wiki?

I had a demo site spun up for another issue so tested this there by adding:

```
.form-managed-file .form-file {
  padding: 1.5rem;
  margin: .5rem;
  border-radius: 5px;
  border: 2px dashed #e9e0c3;
  background-color: #f7f4e9;
  box-shadow: 0 0 4px rgba(0,0,0,.2);
}
```

Also it would be good to add any text you feel appropriate as guidance in the description of the field.

![CleanShot 2024-07-12 at 17 15 17@2x](https://github.com/user-attachments/assets/afe69411-d24d-424b-a090-35e8ed5d5e8c)

**Comment by laryn** [comment]
Please reopen if this wasn't what you needed.

**Comment by laryn** [comment]
I copied this example to https://github.com/backdrop-contrib/html5_upload/wiki

**Comment by danksearle** [comment]
Hi, sorry for not coming back to this, but in the end we decided to not
implement this so I no longer had a need to get this working. I think the
CSS you shared would have been a useful clue for me, back at the time.
